import { b2Transform, b2Vec2, XY } from '../common/b2Math';
import { b2AABB } from '../collision/b2Collision';
import { b2Shape } from '../collision/shapes/b2Shape';
import { b2Contact } from './contacts/b2Contact';
import { b2Joint } from './joints/b2Joint';
import { b2AreaJoint, b2IAreaJointDef } from './joints/b2AreaJoint';
import { b2DistanceJoint, b2IDistanceJointDef } from './joints/b2DistanceJoint';
import { b2FrictionJoint, b2IFrictionJointDef } from './joints/b2FrictionJoint';
import { b2GearJoint, b2IGearJointDef } from './joints/b2GearJoint';
import { b2IMotorJointDef, b2MotorJoint } from './joints/b2MotorJoint';
import { b2IMouseJointDef, b2MouseJoint } from './joints/b2MouseJoint';
import { b2IPrismaticJointDef, b2PrismaticJoint } from './joints/b2PrismaticJoint';
import { b2IPulleyJointDef, b2PulleyJoint } from './joints/b2PulleyJoint';
import { b2IRevoluteJointDef, b2RevoluteJoint } from './joints/b2RevoluteJoint';
import { b2IRopeJointDef, b2RopeJoint } from './joints/b2RopeJoint';
import { b2IWeldJointDef, b2WeldJoint } from './joints/b2WeldJoint';
import { b2IWheelJointDef, b2WheelJoint } from './joints/b2WheelJoint';
import { b2Body, b2IBodyDef } from './b2Body';
import { b2ContactManager } from './b2ContactManager';
import { b2Fixture } from './b2Fixture';
import { b2Island } from './b2Island';
import { b2Profile, b2TimeStep } from './b2TimeStep';
import { b2ContactFilter, b2ContactListener, b2DestructionListener, b2QueryCallback, b2QueryCallbackFunction, b2RayCastCallback, b2RayCastCallbackFunction } from './b2WorldCallbacks';
import { b2ParticleSystem, b2ParticleSystemDef } from '../particle/b2ParticleSystem';
import { b2Controller } from '../controllers/b2Controller';
export declare class b2World {
    m_newFixture: boolean;
    m_locked: boolean;
    m_clearForces: boolean;
    readonly m_contactManager: b2ContactManager;
    m_bodyList: b2Body | null;
    m_jointList: b2Joint | null;
    m_particleSystemList: b2ParticleSystem | null;
    m_bodyCount: number;
    m_jointCount: number;
    readonly m_gravity: b2Vec2;
    m_allowSleep: boolean;
    m_destructionListener: b2DestructionListener | null;
    m_inv_dt0: number;
    m_warmStarting: boolean;
    m_continuousPhysics: boolean;
    m_subStepping: boolean;
    m_stepComplete: boolean;
    readonly m_profile: b2Profile;
    readonly m_island: b2Island;
    readonly s_stack: Array<b2Body | null>;
    m_controllerList: b2Controller | null;
    m_controllerCount: number;
    constructor(gravity: XY);
    SetDestructionListener(listener: b2DestructionListener | null): void;
    SetContactFilter(filter: b2ContactFilter): void;
    SetContactListener(listener: b2ContactListener): void;
    CreateBody(def?: b2IBodyDef): b2Body;
    DestroyBody(b: b2Body): void;
    private static _Joint_Create;
    private static _Joint_Destroy;
    CreateJoint(def: b2IAreaJointDef): b2AreaJoint;
    CreateJoint(def: b2IDistanceJointDef): b2DistanceJoint;
    CreateJoint(def: b2IFrictionJointDef): b2FrictionJoint;
    CreateJoint(def: b2IGearJointDef): b2GearJoint;
    CreateJoint(def: b2IMotorJointDef): b2MotorJoint;
    CreateJoint(def: b2IMouseJointDef): b2MouseJoint;
    CreateJoint(def: b2IPrismaticJointDef): b2PrismaticJoint;
    CreateJoint(def: b2IPulleyJointDef): b2PulleyJoint;
    CreateJoint(def: b2IRevoluteJointDef): b2RevoluteJoint;
    CreateJoint(def: b2IRopeJointDef): b2RopeJoint;
    CreateJoint(def: b2IWeldJointDef): b2WeldJoint;
    CreateJoint(def: b2IWheelJointDef): b2WheelJoint;
    DestroyJoint(j: b2Joint): void;
    CreateParticleSystem(def: b2ParticleSystemDef): b2ParticleSystem;
    DestroyParticleSystem(p: b2ParticleSystem): void;
    CalculateReasonableParticleIterations(timeStep: number): number;
    Step(dt: number, velocityIterations: number, positionIterations: number, particleIterations?: number): void;
    ClearForces(): void;
    QueryAABB(callback: b2QueryCallback, aabb: b2AABB): void;
    QueryAABB(aabb: b2AABB, fn: b2QueryCallbackFunction): void;
    private _QueryAABB;
    QueryAllAABB(aabb: b2AABB, out?: b2Fixture[]): b2Fixture[];
    QueryPointAABB(callback: b2QueryCallback, point: XY): void;
    QueryPointAABB(point: XY, fn: b2QueryCallbackFunction): void;
    private _QueryPointAABB;
    QueryAllPointAABB(point: XY, out?: b2Fixture[]): b2Fixture[];
    QueryFixtureShape(callback: b2QueryCallback, shape: b2Shape, index: number, transform: b2Transform): void;
    QueryFixtureShape(shape: b2Shape, index: number, transform: b2Transform, fn: b2QueryCallbackFunction): void;
    private static QueryFixtureShape_s_aabb;
    private _QueryFixtureShape;
    QueryAllFixtureShape(shape: b2Shape, index: number, transform: b2Transform, out?: b2Fixture[]): b2Fixture[];
    QueryFixturePoint(callback: b2QueryCallback, point: XY): void;
    QueryFixturePoint(point: XY, fn: b2QueryCallbackFunction): void;
    private _QueryFixturePoint;
    QueryAllFixturePoint(point: XY, out?: b2Fixture[]): b2Fixture[];
    RayCast(callback: b2RayCastCallback, point1: XY, point2: XY): void;
    RayCast(point1: XY, point2: XY, fn: b2RayCastCallbackFunction): void;
    private static RayCast_s_input;
    private static RayCast_s_output;
    private static RayCast_s_point;
    private _RayCast;
    RayCastOne(point1: XY, point2: XY): b2Fixture | null;
    RayCastAll(point1: XY, point2: XY, out?: b2Fixture[]): b2Fixture[];
    GetBodyList(): b2Body | null;
    GetJointList(): b2Joint | null;
    GetParticleSystemList(): b2ParticleSystem | null;
    GetContactList(): b2Contact | null;
    SetAllowSleeping(flag: boolean): void;
    GetAllowSleeping(): boolean;
    SetWarmStarting(flag: boolean): void;
    GetWarmStarting(): boolean;
    SetContinuousPhysics(flag: boolean): void;
    GetContinuousPhysics(): boolean;
    SetSubStepping(flag: boolean): void;
    GetSubStepping(): boolean;
    GetProxyCount(): number;
    GetBodyCount(): number;
    GetJointCount(): number;
    GetContactCount(): number;
    GetTreeHeight(): number;
    GetTreeBalance(): number;
    GetTreeQuality(): number;
    SetGravity(gravity: XY, wake?: boolean): void;
    GetGravity(): Readonly<b2Vec2>;
    IsLocked(): boolean;
    SetAutoClearForces(flag: boolean): void;
    GetAutoClearForces(): boolean;
    ShiftOrigin(newOrigin: XY): void;
    GetContactManager(): b2ContactManager;
    GetProfile(): b2Profile;
    Solve(step: b2TimeStep): void;
    _SynchronizeFixturesCheck(): void;
    SolveTOI(step: b2TimeStep): void;
    AddController(controller: b2Controller): b2Controller;
    RemoveController(controller: b2Controller): b2Controller;
}
